language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:chris-lea/protobuf
  - sudo apt-get update
  - sudo apt-get install -qq cmake wget
  - sudo apt-get install -qq boost1.55 libprotobuf-dev protobuf-compiler
  - mkdir -pv build
  - git submodule update --init

before_script:
  cd build && cmake .. -DDEBUG=1

script:
    - make -j2

notifications:
  recipients:
    - jack.wgm@gmail.com
  email:
    on_success: change
    on_failure: always

after_success:
  - wget -q -O /dev/null http://deploy.avplayer.org/deploy.php?sat=9674be14-6107-4c28-b415-5944bf602e47
