language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update
  - sudo apt-get install cmake
  - sudo apt-get install -qq boost1.55
  - mkdir -pv build

before_script:
  cd build && cmake .. -DDEBUG=1

script:
    - make -j2

notifications:
  recipients:
    - jack.wgm@gmail.com
  email:
    on_success: change
    on_failure: always

