language: cpp
compiler:
  - clang

before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:chris-lea/protobuf
  - sudo add-apt-repository -y ppa:b-s-a/ppa
  - sudo apt-get update
  - sudo apt-get install -qq cmake wget
  - sudo apt-get install libsoci-sqlite3.2  libsoci3.2-dev
  - sudo apt-get install -qq boost1.55 libprotobuf-dev protobuf-compiler postgresql-client libpq-dev postgresql-server-dev
  - mkdir -pv build
  - git submodule update --init
  - mkdir -pv buildsoci
  - ( cd buildsoci && cmake ../third_party/soci/src -DCMAKE_INSTALL_PREFIX=/usr && make -j2 && sudo make install )
  - sudo cp third_party/soci/src/cmake/modules/FindPostgreSQL.cmake /usr/share/cmake-2.8/Modules/FindPostgreSQL.cmake

before_script:
  cd build && cmake .. -DDEBUG=1

script:
    - make -j2

notifications:
  recipients:
    - jack.wgm@gmail.com
  email:
    on_success: change
    on_failure: always

after_success:
  - wget -q -O /dev/null http://deploy.avplayer.org/deploy.php?sat=9674be14-6107-4c28-b415-5944bf602e47
